project: default
source:
  repoURL: 'https://charts.jetstack.io'
  targetRevision: v1.13.1
  helm:
    parameters:
      - name: installCRDs
        value: 'true'
  chart: cert-manager
destination:
  namespace: ingress
  name: in-cluster
syncPolicy:
  syncOptions:
    - CreateNamespace=true