apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: counter-ingress
  annotations:
    cert-manager.io/cluster-issuer: prod-issuer
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/metrics {
      deny all;
      return 403;
      }
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: counter-secret
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-redis-app
            port:
              number: 80