name: Docker Build and Publish
on:
  push:
    branches:
      - main
    paths:
      - counter/**
jobs:
  build-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./counter
    steps:
      - uses: actions/checkout@v3
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          directory: ./counter
          image: counter
          dockerfile: counter/Dockerfile
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}